Repository python/devguide, pull requests merged in 2019-08, with the labels that each got.

#477 Update Black URL
  README.rst
Labels: CLA signed, status-do not merge

#523 Fixed typo
  triaging.rst
Labels: CLA signed

#521 Add procedure for adding people to the Python Triage team
  triaging.rst
Labels: CLA signed

#525 Expand "What's New and News Entries" to include Sphinx
  committing.rst
  documenting.rst
Labels: CLA signed

#528 Contribute article to the exploring page
  exploring.rst
Labels: CLA signed, enhancement
