Repository python/devguide, pull requests merged in 2019-09, with the labels that each got.

#531 Adding Stale label
  triaging.rst
Labels: CLA signed

#524 Improve gitbootcamp.rst
  gitbootcamp.rst
Labels: CLA signed, enhancement

#532 Touch up Getting Started
  setup.rst
Labels: CLA signed

#530 Add guidelines for triagers closing PRs
  triaging.rst
Labels: CLA signed, enhancement, github, project: triagers

#534 Fix the example with .. c:var::
  documenting.rst
Labels: CLA signed

#536 Add @pablogsal to CPython Repository Administrators
  devcycle.rst
Labels: CLA signed

#538 Update developer log
  developers.csv
Labels: CLA signed

#539 Update autoconf version
  setup.rst
Labels: CLA signed
