Repository python/devguide, pull requests merged in 2022-05, with the labels that each got.

#700 removed reference of testing through IDLE
  runtests.rst
Labels: CLA signed

#826 bpo-36329: Replace 'make serve' with 'make htmlview'
  Makefile
  make.bat
  tools/serve.py
Labels: enhancement, CLA signed

#857 Document the `htmlview` make target.
  docquality.rst
  documenting.rst
Labels: enhancement

#856 Update `venv` and `clean` make targets
  Makefile
Labels: enhancement

#858 Remove obsolete zh-tw translations link
  documenting.rst
Labels: question

#866 Use sphinx-lint in `make check`.
  Makefile
  gh-faq.rst
  make.bat
  requirements.txt
  setup.rst
  silencewarnings.rst
Labels: enhancement

#704 fixes #613: remove redundant references to setup guide
  index.rst
Labels: CLA signed

#867 Only print `make venv` message when needed.
  Makefile
Labels: bug
