Repository python/devguide, pull requests merged in 2022-10, with the labels that each got.

#957 Fix some markup (including 2 false-positives).
  documentation/style-guide.rst
  internals/parser.rst
  testing/coverage.rst
Labels: bug

#958 Bump `sphinx-lint` to 0.6.4.
  requirements.txt
Labels: enhancement, dependencies

#959 Bump `sphinx-lint` to 0.6.5.
  requirements.txt
Labels: enhancement, dependencies

#855 Document auto-closing keywords for PRs.
  getting-started/git-boot-camp.rst
Labels: enhancement

#963 Bump `sphinx-lint` to 0.6.6.
  requirements.txt
Labels: enhancement, dependencies

#914 Update the triage/triaging.rst page.
  core-developers/committing.rst
  triage/triaging.rst
Labels: enhancement

#965 Use dirhtml builder for Read the Docs
  .readthedocs.yml
Labels: bug
