Repository python/devguide, pull requests merged in 2022-04, with the labels that each got.

#825 Use GitHub usernames in the expert index.
  developers.csv
  experts.rst
Labels: enhancement, CLA signed, github

#814 Document using Github issues as the issue tracker
  appendix.rst
  committing.rst
  communication.rst
  coverage.rst
  docquality.rst
  fixingissues.rst
  gh-faq.rst
  gh-labels.rst
  help.rst
  index.rst
  langchanges.rst
  pullrequest.rst
  setup.rst
  silencewarnings.rst
  stdlibchanges.rst
  tracker.rst
  triaging.rst
Labels: CLA signed

#828 Allow triagers to close PRs if the PR is of very low quality
  triaging.rst
Labels: CLA signed, project: triagers

#824 Add persian to documenting.rst
  documenting.rst
Labels: CLA signed

#801 Add a note about direct test module invocation
  runtests.rst
Labels: CLA signed

#838 Deduplicate translators tables.
  experts.rst
Labels: enhancement

#839 Update my expert index entries.
  experts.rst
Labels: enhancement

#831 Fix some incorrect links
  buildworker.rst
  c-api.rst
  committing.rst
  compiler.rst
  docquality.rst
  motivations.rst
  tracker.rst
Labels: bug

#840 Rename CI check.
  .github/workflows/ci.yml
Labels: enhancement
